// ============================================================
// Static game data: courses, boards, trails, achievements
// ============================================================

export const COURSES = [
  {
    id: "bunny",
    name: "Bunny Hill",
    desc: "初心者向けの緩やかな斜面。まずはここでコツをつかもう。",
    unlockDistance: 0,
    fog: 0x9fd0ea,
    sky: 0xbfe3f5,
    slopeAngle: 26 * Math.PI / 180,
    landingAngle: 34 * Math.PI / 180,
    launchAngle: 12 * Math.PI / 180,
    wind: 0.0,
    lengths: { startFlat: 18, runIn: 70, kicker: 9, landing: 90, outrun: 40 },
  },
  {
    id: "ridge",
    name: "Alpine Ridge",
    desc: "急勾配と細い尾根。風が少し出る。",
    unlockDistance: 260,
    fog: 0x7fa9c9,
    sky: 0x9bc4de,
    slopeAngle: 31 * Math.PI / 180,
    landingAngle: 38 * Math.PI / 180,
    launchAngle: 13 * Math.PI / 180,
    wind: 0.6,
    lengths: { startFlat: 16, runIn: 84, kicker: 9, landing: 110, outrun: 40 },
  },
  {
    id: "canyon",
    name: "Big Air Canyon",
    desc: "巨大な崖から飛び出す。ハイリスク・ハイリターン。",
    unlockDistance: 700,
    fog: 0x5c86ab,
    sky: 0x7ba7cc,
    slopeAngle: 34 * Math.PI / 180,
    landingAngle: 41 * Math.PI / 180,
    launchAngle: 15 * Math.PI / 180,
    wind: 1.2,
    lengths: { startFlat: 14, runIn: 96, kicker: 8, landing: 140, outrun: 40 },
  },
  {
    id: "night",
    name: "Night Session",
    desc: "同じキャニオンを闇の中で。視界は悪いが記録は輝く。",
    unlockDistance: 1400,
    fog: 0x0b1420,
    sky: 0x0b1420,
    night: true,
    slopeAngle: 34 * Math.PI / 180,
    landingAngle: 42 * Math.PI / 180,
    launchAngle: 16 * Math.PI / 180,
    wind: 1.6,
    lengths: { startFlat: 14, runIn: 96, kicker: 8, landing: 150, outrun: 40 },
  },
];

export const BOARDS = [
  { id: "starter", name: "スターターボード", cost: 0, color: 0xdedede,
    speed: 1.0, pop: 1.0, air: 1.0, grip: 1.0,
    desc: "バランスの取れた基本ボード。" },
  { id: "carver", name: "カーバーX", cost: 250, color: 0x3fa9f5,
    speed: 1.12, pop: 0.95, air: 0.95, grip: 1.05,
    desc: "低摩擦で加速に優れる。スピードスター向け。" },
  { id: "airtwist", name: "エアツイスト", cost: 450, color: 0xff7a3c,
    speed: 0.95, pop: 1.05, air: 1.25, grip: 0.95,
    desc: "空中制御力が高くトリック向き。" },
  { id: "bigpop", name: "ビッグポップ", cost: 650, color: 0x8a5cff,
    speed: 1.0, pop: 1.3, air: 1.0, grip: 1.0,
    desc: "踏切の跳躍力を大幅強化。飛距離重視。" },
  { id: "legend", name: "レジェンド", cost: 1200, color: 0xffd35c,
    speed: 1.15, pop: 1.2, air: 1.2, grip: 1.25,
    desc: "全ステータス高水準。真のオールラウンダー。" },
];

export const TRAILS = [
  { id: "snow", name: "パウダースノー", cost: 0, color: 0xffffff, desc: "標準の雪煙。" },
  { id: "ice", name: "アイスブルー", cost: 150, color: 0x7fe0ff, desc: "冷たく輝く青い軌跡。" },
  { id: "fire", name: "ブレイズ", cost: 350, color: 0xff5c3c, desc: "燃えるようなオレンジの軌跡。" },
  { id: "toxic", name: "トキシック", cost: 350, color: 0x9dff4a, desc: "毒々しい蛍光グリーン。" },
  { id: "royal", name: "ロイヤルパープル", cost: 550, color: 0xb26bff, desc: "気品ある紫の軌跡。" },
];

export const ACHIEVEMENTS = [
  { id: "first_air", name: "初めての飛翔", desc: "初めてジャンプに着地する", goal: 1,
    get: p => p.stats.totalLandings >= 1 ? 1 : 0 },
  { id: "hundred_club", name: "100mクラブ", desc: "1回のジャンプで100m以上", goal: 100,
    get: p => Math.min(p.stats.bestSingleDistance, 100) },
  { id: "two_hundred_club", name: "200mクラブ", desc: "1回のジャンプで200m以上", goal: 200,
    get: p => Math.min(p.stats.bestSingleDistance, 200) },
  { id: "three_hundred_club", name: "300mクラブ", desc: "1回のジャンプで300m以上", goal: 300,
    get: p => Math.min(p.stats.bestSingleDistance, 300) },
  { id: "triple_threat", name: "トリプルスレット", desc: "1080°スピンをクラッシュせず着地", goal: 1,
    get: p => p.stats.maxCleanSpinDeg >= 1080 ? 1 : 0 },
  { id: "flip_master", name: "フリップマスター", desc: "フリップ技をクラッシュせず着地", goal: 1,
    get: p => p.stats.maxCleanFlipDeg >= 180 ? 1 : 0 },
  { id: "double_backflip", name: "ダブルバク宙", desc: "720°以上のフリップを着地", goal: 1,
    get: p => p.stats.maxCleanFlipDeg >= 720 ? 1 : 0 },
  { id: "grab_bag", name: "グラブコレクター", desc: "累計10回グラブを成功させる", goal: 10,
    get: p => Math.min(p.stats.totalGrabsLanded, 10) },
  { id: "combo_king", name: "コンボキング", desc: "最大コンボ倍率で着地する", goal: 1,
    get: p => p.stats.maxComboAchieved >= 1.75 ? 1 : 0 },
  { id: "clean_streak", name: "10連続クリーン", desc: "クラッシュせず10回連続着地", goal: 10,
    get: p => Math.min(p.stats.bestCleanStreak, 10) },
  { id: "coin_collector", name: "コインコレクター", desc: "累計1000コイン獲得", goal: 1000,
    get: p => Math.min(p.stats.lifetimeCoins, 1000) },
  { id: "full_garage", name: "ガレージコンプリート", desc: "全ボード・全トレイルを所有", goal: BOARDS.length + TRAILS.length,
    get: p => p.ownedBoards.length + p.ownedTrails.length },
  { id: "globe_trotter", name: "グローブトロッター", desc: "全コースを解放する", goal: COURSES.length,
    get: p => COURSES.filter(c => p.stats.lifetimeDistance >= c.unlockDistance).length },
  { id: "no_fear", name: "ノーフィア", desc: "Night Sessionでクリーン着地", goal: 1,
    get: p => p.stats.nightCleanLanding ? 1 : 0 },
];
